package com.zip.zipandroid.bean

import com.google.gson.annotations.SerializedName

data class ZipUploadUserInfoBean(
    @SerializedName("sunanAsusu")
    val accountName: String,
    @SerializedName("shekarun")
    val age: Int?=-1,
    @SerializedName("idBanki")
    val bankId: String,
    val birthDate: Long,
    @SerializedName("idBanki")
    val birthDateStr: String,
    @SerializedName("idBanki")
    val cardName: String,
    val cardNo: String,
    val cardType: Int?=-1,
    val certEmail: Int?=-1,
    val certIdentity: Int?=-1,
    val channel: String,
    val childrens: Int?=-1,
    val companyAddress: String,
    val companyDistrict: String,
    val payDay: String,
    val companyLocation: String,
    val companyName: String,
    val creditAuthorized: Int?=-1,
    val creditHistory: String,
    val custId: Long,
    val degree: Int?=-1,
    val doubleLoan: Int?=-1,
    val doubleLoanCount: Int?=-1,
    val emergencyContactPerson: String,
    val fatherName: String,
    val firstName: String,
    val idAddress: String,
    val identity: String,
    val identityImg: String,
    val income: String,
    val lengthOfUnemployment: String,
    val timeWorkBegins: Long,
    val ontherIncome: Int?=-1,
    val industry: Int?=-1,
    val employmentStatus: Int?=-1,
    val industryName: String,
    val lastName: String,
    val lastOrderstate: Int?=-1,
    val marry: Int?=-1,
    val mbCustId: Long,
    val mbEmail: String,
    val mbPhone: String,
    val mbStatus: Int?=-1,
    val language: Int?=-1,
    val mbSubject: Long,
    val mid: Long,
    val midName: String,
    val motherName: String,
    val nowAddress: String,
    val postalInfo: String,
    val questions: List<UserCreditListBeanItem>,
    val realname: String,
    val regFrom: Int?=-1,
    val regTime: Long,
    val region: String,
    val sex: String,
    val taxNumber: String,
    val togetherLiver: String,
    val workQuestions: List<WorkQuestion>,
    val workType: String,
)

